spring:
  application:
    name: greeting-microservice

greeting-microservice:
  greeting: "Hola"
  default-value: "La garantia son nosotros"

management:
  endpoints:
    web:
      exposure:
        include:
          - '*'