spring:
  application:
    name: greeting-microservice

greeting-microservice:
  greeting: "Vamos sextar!!"
  default-value: "Em 5 minutos!"

management:
  endpoints:
    web:
      exposure:
        include:
          - '*'