spring:
  application:
    name: greeting-microservice

greeting-microservice:
  greeting: "Vamos em frente"
  default-value: "Todo Mundo!!"

management:
  endpoints:
    web:
      exposure:
        include:
          - '*'