spring:
  application:
    name: greeting-microservice

greeting-microservice:
  greeting: "Empiricus"
  default-value: "Empiricus Empiricus"

management:
  endpoints:
    web:
      exposure:
        include:
          - '*'