spring:
  application:
    name: greeting-microservice

greeting-microservice:
  greeting: "Olá"
  default-value: "Mundo!!"

management:
  endpoints:
    web:
      exposure:
        include:
          - '*'