spring:
  application:
    name: greeting-microservice

greeting-microservice:
  greeting: "Ciao Ciao"
  default-value: "2 Pizza"

management:
  endpoints:
    web:
      exposure:
        include:
          - '*'